title: Produktinformationen
fields:
  -
    handle: private
    field:
      type: toggle
      display: Geschützt
      instructions: 'Sichtbar nur für eingeloggte Benutzer'
      localizable: false
      instructions_position: below
  -
    handle: image
    field:
      max_files: 1
      container: assets
      type: assets
      display: Bild
      localizable: false
  -
    handle: description
    field:
      buttons:
        - h3
        - bold
        - unorderedlist
        - removeformat
        - anchor
        - nobr
      toolbar_mode: floating
      remove_empty_nodes: true
      link_collections:
        - pages
      container: assets
      type: bard
      display: Beschreibung
      localizable: false
