tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: false
              display: Titel
              localizable: false
              validate:
                - required
          -
            handle: preview_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: Vorschaubild
              instructions: 'Optimales Format ist 1:1'
              localizable: false
              instructions_position: below
          -
            handle: blocks
            field:
              type: replicator
              display: Inhalte
              localizable: false
              collapse: true
              sets:
                blocks:
                  display: Inhaltselemente
                  sets:
                    product_information:
                      display: Produktinformationen
                      instructions: 'Produktinformationen hinzufügen'
                      icon: text-formatting-wrap-image-left
                      fields:
                        -
                          import: product_information
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              show_regenerate: true
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
title: Produkte
